공공데이터 MySQL DB 데이터 INSERT
indongzz/daegu_dot_server pull request #7
Opened 2020-08-26 13:31 UTC by HGYEONG

1. XML 기반 공공데이터를 가져와서 파싱
2. MySQL 연동을 위해 dependencies 추가
3. 데이터베이스 설정 yml 추가
3. 파싱 결과를 jpa를 통해 데이터베이스에 삽입

2020-08-26 13:51 UTC, indongzz commented on src/main/java/com/kop/daegudot/domain/opendatas/Opendatas.java
> +                     String telephone){
```suggestion
                     String telephone) {

```
띄워쓰기 넣어주세요~

2020-08-26 13:52 UTC, indongzz commented on src/main/java/com/kop/daegudot/service/opendatas/OpendatasService.java
> +       for(OpendataDto opendataDto : dtoArrayList){ opendatasArrayList.add(opendataDto.toEntity()); }   //Allocate dto to entity
```suggestion
       for (OpendataDto opendataDto : dtoArrayList){ opendatasArrayList.add(opendataDto.toEntity()); }   //Allocate dto to entity

```
띄워쓰기 넣어주세요

2020-08-26 13:53 UTC, indongzz commented on src/main/java/com/kop/daegudot/web/OpenDataConnection.java
> +    public ArrayList<OpendataDto> opendatasHttp(){
```suggestion
    public ArrayList<OpendataDto> opendatasHttp() {

```

띄워쓰기 넣어주세요

2020-08-26 13:55 UTC, indongzz commented on src/main/java/com/kop/daegudot/web/OpenDataConnection.java
> +            for(int i=0; i<nodeList.getLength();i++){
```suggestion
            for (int i = 0; i < nodeList.getLength(); i++) {

```

띄워쓰기..

2020-08-26 13:56 UTC, indongzz commented on src/main/java/com/kop/daegudot/web/OpenDataConnection.java
> +        }catch (Exception e){
```suggestion
        }catch (Exception e) {

```

띄워쓰기 해주세요.

2020-08-26 13:56 UTC, indongzz commented on src/main/java/com/kop/daegudot/web/OpenDataConnection.java
> +    private String getTagValue(String tag, Element element){
```suggestion
    private String getTagValue(String tag, Element element) {

```

띄워쓰기 해주세용

2020-08-26 13:57 UTC, indongzz commented on src/main/java/com/kop/daegudot/web/OpenDataConnection.java
> +        return node.getNodeValue();
```suggestion
        
        return node.getNodeValue();

```

엔터로 구분해주시는게 좋을 것 같아요

2020-08-26 13:59 UTC, indongzz commented on src/main/java/com/kop/daegudot/web/dto/OpendataDto.java
> +            .telephone(telephone).build();
```suggestion
    public Opendatas toEntity() { 
        return Opendatas.builder().address(address)
            .attractContents(attractContents).attractName(attractName).homepage(homepage)
            .telephone(telephone).build();

```

return 구문이 아래로 내려가게 수정해주세요.

2020-08-26 14:01 UTC, indongzz requested changes
띄워쓰기 코멘트 남긴 부분 수정해 주세요.
Entity name이랑 Domain package name을 Opendatas 말고 Places와 같은 다른 식별할 수 있는 이름으로 수정하는게 좋을 것 같아요.

2020-08-31 11:02 UTC, indongzz approved these changes
Good job!

2020-09-01 22:35 UTC, Soyeonu approved these changes
Great Job Girl~!~!

2020-09-02 06:16 UTC, merged